[[agradecimento-aj-payutto-2013]]
= Palavras de Agradecimento

A publicação deste livro, cujo propósito é estar disponível em hotéis e outros
tipos de alojamento, vai ao encontro de uma necessidade de longa data. Outros já
haviam encetado este tipo de projecto mas acabaram sempre por o abandonar; assim
este livro vem finalmente colmatar uma falta importante. Ajahn Jayasaro
escreveu-o sob a forma de Perguntas e Respostas, tornando-o de fácil leitura e
sem um tom demasiado académico. Para além disso ele aplicou a sua vasta
experiência de estudo, ensino e prática budista, para seleccionar os tópicos
adequados. Ele observou e reflectiu quais os assuntos que são normalmente mais
relevantes e importantes de serem explanados.

Ele também aborda neste livro temáticas comummente mal interpretadas e outras
que contêm aspectos importantes e úteis, que são muitas vezes minimizados.
Assim, Ajahn Jayasaro escolheu temáticas adequadas nas quais ele responde às
necessidades dos interessados no Budismo, esclarece mal-entendidos e aponta para
áreas que requerem atenção. Explica e oferece conselhos, esclarecendo os
leitores sobre conceitos fundamentais do Budismo.

Há uma temática muito benéfica que impregna toda a expressão deste livro: o
elegante e meticuloso cultivo de tudo quanto de nobre existe no coração e na
mente

Aqueles que visitam países como a Tailândia encontram actividades, costumes,
tradições e comportamentos que reflectem o espírito Budista, e estes podem ser
intrigantes e fora do comum. Este livro ajudá-los-á a compreender melhor estas
experiências, podendo eles assim não só desfrutar das suas viagens, como também
terem uma aprendizagem de vida mais rica.

Pode haver leitores que estejam também a passar por um período mais difícil nas
suas vidas ou a viverem algum tipo de infelicidade e quiçá as compreensões e
realizações despoletadas por esta leitura possam ajudar a resolver algumas
dessas dificuldades.

Por último, quando os leitores se encontrarem de volta nos seus quartos de hotel
e procurarem descontrair, este livro pode ser um companheiro que nutre os seus
corações e as suas mentes. Ainda que somente aberto com o objectivo de relaxar,
poderá oferecer uma sensação de paz, bondade e clareza.

Eu gostaria de acrescentar o meu sincero agradecimento ao ‘Buddhadasa Indapanno
Archives’ pelo esforço e dedicação dos seus membros na publicação deste livro,
de forma a este poder estar disponível em hotéis e hospedarias. É uma oferta de
Dhamma que disseminará conhecimento, compreensão e integridade, contribuindo
para uma felicidade verdadeira e duradoura, partilhada por pessoas à volta do
mundo.

Phra Brahmagunabhorn (P. A. Payutto) +
9 de Maio de 2013
