[[bencaos]]
= Cântico de Bênçãos

____
Evitar os tolos, +
Associar-se aos Sábios, +
E honrar quem é digno de honra. +
Estas são as maiores bênçãos.

Viver em locais adequados, +
Com os frutos das boas acções passadas, +
Guiado pelo caminho correcto. +
Estas são as maiores bênçãos.

Proficiente em estudos e ofícios, +
Com disciplina sublimemente treinada, +
E discurso verdadeiro agradável ao ouvido. +
Estas são as maiores bênçãos.

Apoiar os pais, +
Zelar pela família, +
E ter uma vida inofensiva para os demais. +
Estas são as maiores bênçãos.

Generosidade e uma vida honesta, +
Oferecer ajuda a familiares e amigos, +
Agir de forma que não promova remorsos. +
Estas são as maiores bênçãos.

Resoluto a controlar-se, a abandonar os caminhos do mal, +
Evitar intoxicantes que entorpeçam a mente, +
E ser diligente em todas as ocasiões. +
Estas são as maiores bênçãos.

Respeito e humildade, +
Contentamento e gratidão, +
Ouvir o Dhamma frequentemente ensinado. +
Estas são as maiores bênçãos.

Paciência e vontade para aceitar as próprias falhas, +
Visitar os respeitáveis buscadores da verdade, +
E partilhar o Dhamma frequentemente. +
Estas são as maiores bênçãos.

Dedicar-se ardentemente à Vida Santa, +
Ver as Nobres Verdades directamente por si +
E realizar o Nibbana. +
Estas são as maiores bênçãos.

Ainda que em contacto com o mundo, +
A mente mantem-se inabalável, +
Perfeitamente segura além de toda a aflição. +
Estas são as maiores bênçãos.

Aqueles que seguem este caminho, +
Conhecem a Victória onde quer que vão, +
E qualquer lugar para eles é seguro. +
Estas são as maiores bênçãos.

Maṅgala Sutta, Sutta Nipāta 24
____
