[[preface-bia-2020]]
= Prefácio

a edição deste livro foi impressa em 2013 de forma a celebrar três
ocasiões auspiciosas: os 2600 anos desde a iluminação do Buda, o 100º
aniversário de Sua Santidade Somdet Phra Sangharaja Chao Krom Luang
Vajirananasamvara (Charoen Savaddhano), o 19º Patriarca Supremo do Reino da
Tailândia, e o 84º aniversário de Sua Majestade Phrabat Somdet Phra Paraminthra
Maha Bhumibol Adulyadej (Rama IX). Foram distribuídas mais de 82.996 cópias da
primeira edição em 289 hotéis (em 39 províncias) e em bibliotecas, templos e
escolas, quer dentro quer fora da Tailândia.

Para celebrar o 10º aniversário da Buddhadasa Indapanno Archives Foundation
(BIA) in 2020, uma segunda edição foi publicada pela Fundação, em colaboração
com Ajahn Jayasaro e com a Panyaprateep Foundation. Para além do Inglês, a nova
edição, concisa e fácil de transportar, foi também traduzida em muitas outras
línguas, incluindo Chinês, Português, Russo e Francês.

Espera-se que a distribuição deste livro continue a beneficiar grandemente o
público, indo ao encontro das palavras do Somdet Phra Buddhaghosacariya (P.A.
Payutto): uma oferta de Dhamma que difundirá conhecimento, compreensão e sentido
de justiça, contribuindo para uma felicidade verdadeira e duradoura entre as
pessoas de todo o mundo.

“Por fora e Por Dentro” irá essencialmente beneficiar quer os turistas na
Tailândia, quer as restantes pessoas do globo. Para além de enriquecer vidas,
este livro ajudará a nutrir as mentes e os corações dos leitores e proporcionará
uma noção de paz, bondade e clareza, tornando-o numa verdadeira oferta de
Dhamma, tal como foi projectado para ser.

Buddhadasa Indapanno Archives Foundation (BIA) +
Fevereiro de 2020

